"""Figma REST API integration for creating actual content."""

import os
import httpx
import logging

logger = logging.getLogger(__name__)

# Hardcoded path for reliability
ENV_PATH = "/home/sadhikari/.openclaw/workspace-rewind-cleanup/porthon/.env"


def _get_api_key():
    """Lazy load API key."""
    from dotenv import load_dotenv
    load_dotenv(ENV_PATH)
    return os.environ.get("FIGMA_API_KEY")


class FigmaAPI:
    """Direct Figma REST API client."""
    
    def __init__(self, api_key: str = None):
        self.api_key = api_key or _get_api_key()
        if not self.api_key:
            raise ValueError("FIGMA_API_KEY not found")
        self.headers = {"X-Figma-Token": self.api_key}
    
    async def add_comment(self, file_key: str, message: str, client_meta: dict = None) -> dict:
        """Add a comment to a file."""
        async with httpx.AsyncClient() as client:
            payload = {"message": message}
            if client_meta:
                payload["client_meta"] = client_meta
            
            resp = await client.post(
                f"https://api.figma.com/v1/files/{file_key}/comments",
                headers=self.headers,
                json=payload
            )
            resp.raise_for_status()
            return resp.json()
    
    async def create_design_challenge_board(self, file_key: str, challenges: list, 
                                           scenario_title: str, milestones: list = None) -> dict:
        """Create a structured challenge board in Figma."""
        
        board = f"""# 🎯 {scenario_title}

## Weekly Roadmap

"""
        
        for i, challenge in enumerate(challenges, 1):
            board += f"""
### Week {i}: {challenge.get('title', 'Untitled')}

**Brief:** {challenge.get('brief', 'N/A')}

**Skills:** {', '.join(challenge.get('skill_focus', []))}

**Duration:** {challenge.get('estimated_hours', '?')} hours

**Portfolio Worthy:** {'✅' if challenge.get('portfolio_worthy') else '❌'}

---

"""
        
        if milestones:
            board += """## Milestones

"""
            for m in milestones:
                board += f"- **{m.get('title', 'TBD')}:** {m.get('target', 'N/A')}\n"
            board += "\n"
        
        board += """## 🎯 How to Use This Board

1. **Week 1:** Complete Brief → Share for feedback
2. **Week 2:** Iterate based on feedback
3. **Week 3:** Final polish → Add to portfolio!

---
*Generated by Questline AI 🤖*
"""
        
        return await self.add_comment(file_key, board)


def get_figma_api() -> FigmaAPI:
    return FigmaAPI()
