"""Figma Creator Worker - Creates actual Figma content using REST API.

This worker extends beyond Composio's read-only capabilities by using
the Figma REST API directly to create comments/boards.

Actions:
- create_challenge_board: Create a structured challenge board in Figma
- create_milestone_tracker: Create a milestone tracking board
"""

from __future__ import annotations

import logging
import os

from deepagent.workers.base import BaseWorker, WorkerExecution
from integrations.figma_api import get_figma_api

logger = logging.getLogger(__name__)


class FigmaCreatorWorker(BaseWorker):
    worker_id = "figma_creator_worker"
    label = "Figma Creator"

    ACTIONS = {
        "create_challenge_board": "_create_challenge_board",
        "create_milestone_tracker": "_create_milestone_tracker",
        "create_board": "_create_challenge_board",
    }

    async def execute(self, action: str, payload: dict) -> WorkerExecution:
        handler_name = self.ACTIONS.get(action)
        if not handler_name:
            return WorkerExecution(ok=False, message=f"Unknown action: {action}")
        handler = getattr(self, handler_name)
        return await handler(payload)

    def _get_default_file_key(self) -> str:
        """Default Figma file to write to."""
        return os.environ.get("FIGMA_DEFAULT_FILE_KEY", "clVA1E7bz8iZDqDCbf7XKu")

    async def _create_challenge_board(self, payload: dict) -> WorkerExecution:
        """Create a structured challenge board in Figma."""
        file_key = payload.get("file_key", self._get_default_file_key())
        scenario_title = payload.get("scenario_title", "Questline Challenge")
        
        # Get challenges from payload or generate
        challenges = payload.get("challenges", [
            {
                "title": "Conversion-First Landing Page",
                "brief": "Redesign a local service landing page to optimize inquiry conversion",
                "skill_focus": ["layout", "CTA hierarchy", "copy integration"],
                "estimated_hours": 4,
                "portfolio_worthy": True,
            },
            {
                "title": "Austin Brand Motion System",
                "brief": "Create a lightweight motion system for a local creator collective",
                "skill_focus": ["motion design", "component systems"],
                "estimated_hours": 4,
                "portfolio_worthy": True,
            },
            {
                "title": "Case Study Narrative Sprint",
                "brief": "Turn one shipped project into a KPI-anchored case study",
                "skill_focus": ["storytelling", "visual sequencing"],
                "estimated_hours": 4,
                "portfolio_worthy": True,
            },
        ])
        
        milestones = payload.get("milestones", [
            {"title": "Week 1", "target": "Brief + concepts"},
            {"title": "Week 2", "target": "Mid-fidelity exploration"},
            {"title": "Week 3", "target": "Final polish + share-out"},
        ])
        
        try:
            figma = get_figma_api()
            
            # Build structured board
            board = f"""# 🎯 {scenario_title}

## Weekly Roadmap

"""
            
            for i, challenge in enumerate(challenges, 1):
                board += f"""
### Week {i}: {challenge.get('title', 'Untitled')}

**Brief:** {challenge.get('brief', 'N/A')}

**Skills:** {', '.join(challenge.get('skill_focus', []))}

**Duration:** {challenge.get('estimated_hours', '?')} hours

**Portfolio Worthy:** {'✅' if challenge.get('portfolio_worthy') else '❌'}

---

"""
            
            board += f"""
## Milestones

"""
            for m in milestones:
                board += f"- **{m.get('title', 'TBD')}:** {m.get('target', 'N/A')}\n"
            
            board += """
## 🎯 How to Use

1. **Week 1:** Complete Brief → Share for feedback
2. **Week 2:** Iterate based on feedback  
3. **Week 3:** Final polish → Add to portfolio!

---
*Generated by Questline AI 🤖*
"""
            
            # Post to Figma via REST API
            result = await figma.add_comment(file_key, board)
            
            if "err" in result:
                return WorkerExecution(
                    ok=False,
                    message=f"Failed to create board: {result.get('err')}",
                    data=result
                )
            
            return WorkerExecution(
                ok=True,
                message=f"Created challenge board in Figma!",
                data={
                    "file_key": file_key,
                    "challenges": len(challenges),
                    "comment_id": result.get("id"),
                    "message": "Check your Figma file for the new challenge board!"
                }
            )
            
        except Exception as e:
            logger.error(f"Figma creator error: {e}")
            return WorkerExecution(
                ok=False,
                message=f"Error creating board: {str(e)}",
                data={"error": str(e)}
            )

    async def _create_milestone_tracker(self, payload: dict) -> WorkerExecution:
        """Create a milestone tracking board."""
        file_key = payload.get("file_key", self._get_default_file_key())
        milestones = payload.get("milestones", [])
        
        tracker = "# 🎯 Milestone Tracker\n\n"
        
        for m in milestones:
            status = m.get("status", "pending")
            emoji = {"done": "✅", "in_progress": "🔄", "pending": "⬜"}.get(status, "⬜")
            tracker += f"- {emoji} **{m.get('title', 'Untitled')}** — {m.get('target', '')}\n"
        
        tracker += "\n*Updated by Questline AI*"
        
        try:
            figma = get_figma_api()
            result = await figma.add_comment(file_key, tracker)
            
            return WorkerExecution(
                ok=True,
                message="Created milestone tracker!",
                data={"comment_id": result.get("id")}
            )
        except Exception as e:
            return WorkerExecution(ok=False, message=str(e))
